# Datasource configuration - PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/melita_order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
