order:
  message: This is a message from OAS.yml
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: melita.order.exchange
    queue:
      name: melita.order.queue
    routing:
      key: order.create
