server:
  port: 8081
order:
  message: This is a message from OAS.yml

# MessageQueue configuration
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: melita.order.exchange
    queue:
      name: melita.order.queue
    routing:
      key: order.create
  cloud:
    gateway:
      routes:
        - id: order-accept-service
          predicates:
            - Path=/orders
          filters:
            - JwtAuthenticationFilter
