# Server hosted port
server:
  port: 8082

# MessageQueue configuration
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: melita.order.exchange
    queue:
      name: melita.order.queue
    routing:
      key: order.create
  datasource:
    schema: order_process
   
# Flyway configuration - PostgreSQL
  flyway:
    baseline-on-migrate: true
    schemas: order_process
    locations: classpath:db/flyway/migration  
  
