# Server hosted port
server:
  port: 8082

# MessageQueue configuration
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: melita.order.exchange
    queue:
      name: melita.order.queue
    routing:
      key: order.create

  # Datasource configuration - PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/order_process
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
# Flyway configuration - PostgreSQL
  flyway:
    baseline-on-migrate: true
    schemas: melita_order
    locations: classpath:db/flyway/migration  
  
