server:
  port: 8081
order:
  message: This is a message from OAS.yml

# MessageQueue configuration
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: melita.order.exchange
    queue:
      name: melita.order.queue
    routing:
      key: order.create
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: order
    locations: classpath:db/flyway/migration
