order:
  message: This is a message from OAS.yml
server:
  port: 8082
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: melita.order.exchange
    queue:
      name: melita.order.queue
    routing:
      key: order.create
  datasource:
    url: jdbc:postgresql://localhost:5432/order_process
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
